### ISSUE TITLE
GenericObject logo not showing

### ISSUE THREAD

**Issue by arturogf93** [chiiya/passes#15]
I'am trying to make a generic pass with a logo:

$object = new GenericObject(
.........
logo: Image::make('https://s3.amazonaws.com/.........'),
.........
);
![Screen Shot 2023-03-09 at 11 46 45](https://user-images.githubusercontent.com/6773415/224112019-7aaaf13d-904a-4d6e-aba9-8fea11e3ebf0.jpg)

**Comment by kerattila** [comment]
Hi @arturogf93, 

The image you're trying to use is public or private? Other images are working properly (eg. heroImage) ?

**Comment by arturogf93** [comment]
It is public.

**Comment by arturogf93** [comment]
I realized that i didn't have a logo on my business information:

![image](https://user-images.githubusercontent.com/6773415/234653922-bb10c3ec-c88f-4b12-89b8-c6384020c57a.png)

It works fine now.
