### ISSUE TITLE
Google API: Empty properties at classes and objects should not send

### ISSUE THREAD

**Issue by Gollm** [chiiya/passes#22]
It is recommended not to send empty properties to all the API endpoints. 

Besides erroneous cross effects, this feature is needed, for example, to add multiple event tickets to the wallet, since the JWT URL has a limit of 1,800 characters, resulting in error messages even for a few tickets.

In the current implementation, the entire object with all its properties is output in any case.

instead of
`{
  "iss": "iss@iss.iam.gserviceaccount.com",
  "aud": "google",
  "typ": "savetoandroidpay",
  "payload": {
    "eventTicketObjects": [
      {
        "seatInfo": null,
        "reservationInfo": null,
        "ticketHolderName": null,
        "ticketNumber": null,
        "ticketType": null,
        "faceValue": null,
        "linkedOfferIds": [],
        "hexBackgroundColor": null,
        "messages": [],
        "locations": [],
        "hasLinkedDevice": null,
        "disableExpirationNotification": null,
        "id": "issuerID.objectID",
        "classId": "issuerID.classID",
        "state": "ACTIVE",
        "barcode": null,
        "validTimeInterval": null,
        "smartTapRedemptionValue": null,
        "groupingInfo": null,
        "imageModulesData": [],
        "textModulesData": [],
        "linksModuleData": null,
        "appLinkData": null,
        "heroImage": null,
        "rotatingBarcode": null,
        "hasUsers": null
      },
      {
        "seatInfo": null,
        "reservationInfo": null,
        "ticketHolderName": null,
        "ticketNumber": null,
        "ticketType": null,
        "faceValue": null,
        "linkedOfferIds": [],
        "hexBackgroundColor": null,
        "messages": [],
        "locations": [],
        "hasLinkedDevice": null,
        "disableExpirationNotification": null,
        "id": "issuerID.objectID",
        "classId": "issuerID.classID",
        "state": "ACTIVE",
        "barcode": null,
        "validTimeInterval": null,
        "smartTapRedemptionValue": null,
        "groupingInfo": null,
        "imageModulesData": [],
        "textModulesData": [],
        "linksModuleData": null,
        "appLinkData": null,
        "heroImage": null,
        "rotatingBarcode": null,
        "hasUsers": null
      }
    ]
  }
}`

it should be
`{
  "iss": "iss@iss.iam.gserviceaccount.com",
  "aud": "google",
  "typ": "savetoandroidpay",
  "payload": {
    "eventTicketObjects": [
      {
        "id": "issuerID.objectID",
        "classId": "issuerID.classID",
        "state": "ACTIVE",
      },
      {
        "id": "issuerID.objectID",
        "classId": "issuerID.classID",
        "state": "ACTIVE"
      }
    ]
  }
}`

see also google docs:
https://developers.google.com/wallet/tickets/events/use-cases/save-multiple-passes

**Comment by Gollm** [comment]
If you know exactly your needed properties, i figured out, you can use this

`$jwtObject->only('id', 'classId', 'state');`

**Comment by Synchro** [comment]
I've noticed this too, but I'm wondering if it's a bug because the `Component` class contains a `removeEmptyValues` method that strips `null` values when `jsonSerialize` is called – but it looks like it's not being used, or doesn't work properly, because I too end up with nulls in my JSON.

Update: I stuck a `dd()` in `Component::jsonSerialize()` and confirmed that this code is never run. The conversion to JSON is done inside the `JWT::encode` method (in the Firebase JWT implementation), but for some reason the `jsonSerialize` method (given that the `Component` class declares it's `JsonSerializable`) never triggers.

**Comment by Synchro** [comment]
I think I have tracked this down. If I create a `Component` instance and convert it to JSON manually, it works correctly, and `jsonSerialize` is called:

```php
$object = new GenericObject(
...
);
$json = json_encode($object);
```

but if I pass that same object to be wrapped into a JWT:

```php
        $jwt = (new GoogleJWT(
            [
                'iss'     => $credentials->client_email,
                'key'     => $credentials->private_key,
                'origins' => ['https://api.example.com'],
            ]
        ))->addGenericObject($object)->sign();
```

`jsonSerialize` is never called.

When `JWT::sign()` is called, it pre-processes the payload to add a JWT `iat` timestamp. Unfortunately this process converts the `Component` instance to a plain array, and thus it loses any connection to the `Component` class that defines the `jsonSerializable` method, and never gets a chance to strip its empty values.

PR incoming...
